include: package:flutter_lints/flutter.yaml

# Additional rules can be found at https://dart-lang.github.io/linter/lints/
linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - sort_child_properties_last
    - use_key_in_widget_constructors

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
